apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reactjs-app.fullname" . }}-deployment
  labels:
    {{- include "reactjs-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "reactjs-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reactjs-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
