apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactjs-app.fullname" . }}-service
  labels:
    {{- include "reactjs-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "reactjs-app.selectorLabels" . | nindent 4 }}
