apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs-app
  template:
    metadata:
      labels:
        app: reactjs-app
    spec:
      containers:
        - name: reactjs-app
          image: muru777/reactjs_app_kube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
