apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  selector:
    app: reactjs-app
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
    targetPort: 8080
    protocol: TCP
